-- Seed evaluation data from CSV
-- This populates sample evaluation records from the evaluations grid

INSERT INTO evaluations (
    evaluation_id, company_name, ticker, exchange, sector, industry,
    analysis_date, analysis_time, timezone, analysis_type, ownership_status,
    investment_thesis_summary, industry_structure, industry_trend, competitive_position,
    moat_status, customer_economics, pricing_power, customer_stickiness, optionality,
    management_quality, capital_allocation, incentive_alignment, corporate_governance,
    economic_conversion_quality, bear_case_severity, external_vulnerability,
    downside_asymmetry, upside_asymmetry, thesis_break_probability, market_expectations,
    valuation, portfolio_fit, opportunity_cost, business_quality, investment_attractiveness,
    thesis_status, overall_confidence, primary_bull_case, primary_bear_case, biggest_unknown,
    buy_trigger, add_trigger, hold_condition, reduce_trigger, exit_trigger,
    what_improved_since_last, what_deteriorated_since_last, decision, decision_rationale,
    full_factor_detail
) VALUES 
(
    'EICHERMOT-20260821-1400',
    'Eicher Motors Limited',
    'EICHERMOT',
    'NSE',
    'Automobile · Two-Wheelers',
    'Premium / Middleweight Motorcycles (250-750cc)',
    '2026-08-21'::DATE,
    '14:00',
    'IST',
    'INITIAL',
    'Existing Holding',
    'Royal Enfield''s brand moat in the 250-750cc middleweight motorcycle segment (~85-90% domestic share, global category leader) lets Eicher sidestep the volume/price wars that squeeze mass-market two-wheeler makers. Compounding is driven by premium pricing power, a near-debt-free balance sheet reinvested at ~23% ROCE, and optionality from exports and EV entry.',
    'ATTRACTIVE',
    'STABLE',
    'DOMINANT',
    'STABLE (Brand)',
    'Enthusiast-driven purchase with a strong recurring ecosystem — accessories, apparel, owner clubs, guided rides — that extends monetization beyond the motorcycle sale itself. Retail-diversified customer base (low concentration risk). Moderate upgrade cycle as owners trade up within the Royal Enfield range.',
    'Adequate',
    'Strong',
    'Adequate',
    'Strong',
    'Strong',
    'Neutral',
    'Strong',
    'Strong',
    'Medium',
    'Medium',
    'If the EV transition (Flying Flea) fails or slips further while margin compression persists, the rich multiple could de-rate from ~40x toward the ~28-30x sector average — a 25-30% valuation-driven downside even with flat earnings, on top of any earnings miss.',
    'If Flying Flea successfully captures a new EV-native customer base while ICE Royal Enfield holds its middleweight share, the market may be underpricing a second growth vector — international CKD expansion and the VECV commercial-EV JV add further optionality not obviously reflected in current numbers.',
    'LOW-MODERATE',
    'HIGH',
    'DEMANDING',
    'One of the larger single-stock weights in the portfolio; a genuine quality compounder rather than a speculative position, but the current entry point (if adding) offers little margin of safety.',
    'Capital is otherwise well-deployed across the portfolio''s defence and financials names; no strong case that redeploying out of Eicher into a specific alternative is currently justified given the thesis remains intact.',
    'STRONG',
    'Genuinely high-quality business (brand moat, capital discipline, cash conversion) but not without real near-term watch items — margin trajectory and EV execution timing.',
    'INTACT',
    'Medium',
    'Dominant, brand-protected niche with pricing power, near-debt-free balance sheet, ~23% ROCE with capital employed roughly doubling over 5 years without return dilution, and consistent ~40% dividend CAGR — a rare combination of moat and capital discipline.',
    'Premium (>350cc) segment sales have softened while management explicitly prioritizes growth over margin, suggesting real near-term margin pressure; layered on a rich valuation (37-47x P/E vs ~30x sector average) and high FII ownership (~32%) that amplifies sensitivity to global risk-off flows.',
    'Whether Flying Flea can convert Royal Enfield''s ICE brand loyalty into genuine EV-era demand before competitors (Bajaj-Triumph, Chinese entrants) establish themselves in the same segment.',
    'P/E compresses to within ~10% of the ~30x sector average while brand/thesis metrics (segment share, ROCE, dividend growth) remain intact.',
    'Flying Flea launches with credible early traction AND premium (>350cc) segment sales stabilize or recover for 2+ consecutive quarters.',
    'Middleweight segment share stays above ~80%, ROCE and dividend growth trends remain intact, and margin compression does not deepen beyond current levels.',
    'Premium segment revenue share declines for 3+ consecutive quarters, or margin compression deepens with no credible recovery plan from management.',
    'Middleweight segment share falls durably below ~75%, Flying Flea slips again beyond FY27 while competitors ship credible electric middleweights first, or promoter (Lal family) stake falls meaningfully below ~45%.',
    NULL,
    NULL,
    'HOLD',
    'Thesis remains intact — genuine brand moat and capital discipline unchanged — but current valuation is demanding and near-term margin/EV-execution are live watch items, so this is a hold rather than an add at today''s price.',
    '{"factors":[{"name":"Investment Thesis","assessment":"Strong","narrative":"Royal Enfield''s brand moat in the 250-750cc middleweight segment (~85-90% share) lets Eicher avoid the price wars squeezing mass-market rivals, compounding via premium pricing and disciplined reinvestment at ~23% ROCE.","confidence":"High"}]}'::JSON
),
(
    'CMSINFO-20260822-0914',
    'CMS Info Systems Limited',
    'CMSINFO',
    'NSE',
    'Financial Services',
    'Cash Management & Banking Technology',
    '2026-08-22'::DATE,
    '09:14',
    'IST',
    'INITIAL',
    'Existing Holding',
    'Leverage route density scale across 150,000+ touchpoints (~46% ATM cash market share) to generate resilient cash flows while reinvesting in tech managed services (AI monitoring, banking automation) driving >25% ROCE and 15%+ EPS growth.',
    'ATTRACTIVE',
    'STRUCTURALLY IMPROVING',
    'DOMINANT',
    'WIDENING (Route Density & Switching Costs)',
    'Multi-year contracts (3-5 yrs) with commercial banks ensuring stable recurring cash flows; >80% contractual revenue.',
    'Adequate',
    'Strong',
    'Strong',
    'Strong',
    'Strong',
    'Positive',
    'Strong',
    'Strong',
    'Medium',
    'Low',
    'Limited downside supported by ~15-18x P/E valuation, zero net debt, >25% ROCE, and strong operating cash flow generation.',
    'Re-rating potential as tech-enabled managed services expand beyond 35% of total revenue, unlocking 18-20% EPS growth.',
    'LOW-MODERATE',
    'MODERATE',
    'ATTRACTIVE',
    'High quality capital compounding opportunity relative to broader market valuations.',
    'STRONG',
    'High quality market leader trading at attractive valuation with strong cash generation and optionality.',
    'INTACT',
    'High',
    'Unmatched route density scale combined with accelerated scaling of high-margin Managed Services (AI remote monitoring, banking automation). As technology solutions expand to >35% of total revenue, CMS re-rates from a logistics operator to a critical banking technology partner, delivering 18-20% EPS CAGR and >28% ROCE.',
    'Rapid digital adoption (UPI/CBDC) causes a structural contraction in Indian cash usage and nationwide ATM closures. Fixed costs in cash transit networks compress operating margins while new tech services fail to offset cash logistics revenue declines.',
    'Speed and extent of cash usage displacement by UPI/CBDC vs rate of scaling in non-cash tech managed services.',
    'Current valuation (~15-18x P/E) providing margin of safety alongside >25% ROCE and market dominance.',
    'Managed Services segment revenue grows >25% YoY or stock valuation pulls back below 15x P/E.',
    'Business continues delivering 12-15% earnings growth with ROCE > 22% and stable cash logistics volumes.',
    'Managed Services revenue growth slows below 10% or operating EBITDA margins fall below 22%.',
    'Absolute Cash-in-Circulation declines >15% YoY for 2 consecutive reporting years or major governance/accounting red flags emerge.',
    NULL,
    NULL,
    'BUY',
    'Market-dominant, net-debt-free business generating >25% ROCE and strong operating cash flows. At ~15-18x P/E, market overemphasizes digital payment disruption while underestimating route density moat and managed services expansion.',
    '{"factors":[{"name":"Investment Thesis","assessment":"STRONG","narrative":"Dominant position in essential banking infrastructure combined with expansion into tech-enabled managed services creates a durable capital compounding engine.","confidence":"High"}]}'::JSON
),
(
    'BLUESTARCO-20260822-0930',
    'Blue Star Limited',
    'BLUESTARCO',
    'NSE',
    'Consumer Durables / Capital Goods',
    'Air Conditioning & Commercial Refrigeration / MEP Projects',
    '2026-08-22'::DATE,
    '09:30',
    'IST',
    'INITIAL',
    'Existing Holding',
    'Premier Indian cooling and MEP engineering leader compounding value through low room AC penetration (~8-10% in India), commercial refrigeration expansion (cold chain, QSR), and data center MEP buildouts, supported by >21% ROCE.',
    'ATTRACTIVE',
    'STRUCTURALLY IMPROVING',
    'STRONG',
    'STABLE (Brand, Distribution & Engineering Expertise)',
    'B2C room AC is transactional with seasonal peaks; B2B EMPAC has long-term multi-year project contracts with ~Rs 6,923 Cr order book visibility.',
    'Adequate',
    'Adequate',
    'Strong',
    'Strong',
    'Strong',
    'Positive',
    'Strong',
    'Adequate',
    'Medium',
    'Medium',
    'Valuation risk is high at ~60x P/E; weather dependency (mild summers) can compress seasonal earnings severely.',
    'Accelerated room AC adoption (target 20%+ market share) and rapid data center / cold chain expansion driving 20%+ profit growth.',
    'LOW-MODERATE',
    'HIGH',
    'DEMANDING',
    'High given ~60x P/E valuation relative to single-digit near-term volume growth risks.',
    'STRONG',
    'Strong underlying business quality but demanding valuation limits margin of safety for new capital.',
    'INTACT',
    'High',
    'Structural increase in Indian room AC penetration from ~9% to 20%+ combined with leadership in data center MEP projects and commercial cold chain leads to 20%+ earnings CAGR and market share gains.',
    'Monsoon unpredictability/mild summers severely hit seasonal Q1 room AC margins; intense price competition from Daikin/Lloyd compresses margins while working capital stretches in MEP projects.',
    'Weather predictability (summer intensity) and ability to pass on raw material/commodity price spikes in consumer ACs.',
    'Stock price pulls back to <40x P/E (~Rs 1,000-1,100) or room AC market share expands beyond 16% with operating margins >8.5%.',
    'For existing holders: order book in EMPAC grows >20% YoY and room AC market share gains continue.',
    'Revenue growth remains >12% with ROCE sustained above 18% and EBITDA margins >7.5%.',
    'Operating EBITDA margin compresses below 6.5% for two consecutive quarters or MEP working capital days exceed 110 days.',
    'Room AC market share drops below 10% permanently or major loss-making project cost overruns hit EMPAC division.',
    NULL,
    NULL,
    'WATCH',
    'Blue Star is a high-quality cooling leader with >21% ROCE and strong structural tailwinds in room ACs and data center MEP projects. However, at ~60x trailing P/E and current weather/margin volatility, valuation is DEMANDING, offering insufficient margin of safety for initiating a new position.',
    '{"factors":[{"name":"Investment Thesis","assessment":"STRONG","narrative":"Premier Indian cooling and MEP engineering conglomerate benefiting from structural tailwinds in India''s low room AC penetration, data center buildouts, and commercial refrigeration expansion.","confidence":"High"}]}'::JSON
),
(
    'ETERNAL-20260822-0946',
    'Eternal Limited',
    'ETERNAL',
    'NSE',
    'Consumer Internet / Technology',
    'Food Delivery / Quick Commerce / Consumer Internet',
    '2026-08-22'::DATE,
    '09:46',
    'IST',
    'INITIAL',
    'Existing Holding',
    'Eternal has a strong multi-engine compounding thesis built around Zomato food delivery, Blinkit quick commerce and adjacent businesses such as District and Hyperpure. The business quality is strong, but the current valuation embeds very high expectations; the key question is whether rapid growth can convert into durable cash flow and high ROCE without excessive reinvestment.',
    'NEUTRAL',
    'STRUCTURALLY IMPROVING',
    'STRONG',
    'STABLE-WIDENING (Scale, Network Effects, Distribution, Brand, Data)',
    'Strong repeat usage and platform/network effects; exact cohort LTV/CAC economics are not fully disclosed in the reviewed public summary data.',
    'Adequate',
    'Strong',
    'Strong',
    'Strong',
    'Strong',
    'Positive',
    'Strong',
    'Strong',
    'High',
    'Medium',
    'High at the current valuation because earnings and margin expectations are elevated; a slowdown in Blinkit growth or a weaker-than-expected margin trajectory could cause substantial multiple compression.',
    'Meaningful if Blinkit sustains high growth while reaching durable high-teens or better unit economics, Zomato compounds profitably, and District/Hyperpure become material high-return businesses.',
    'LOW-MODERATE',
    'EXTREME',
    'EXTREME',
    'High: capital committed at the current valuation competes with established high-quality businesses available at lower earnings expectations.',
    'STRONG',
    'Strong business with improving economics and substantial optionality, but current valuation leaves little margin of safety for a new investor.',
    'INTACT',
    'Medium',
    'Eternal becomes India''s dominant consumer-internet platform across food delivery and quick commerce, with Blinkit scaling into a structurally high-return business while Zomato funds group-level growth and adjacent businesses add incremental value.',
    'Competitive intensity and capital requirements in quick commerce remain higher than expected, causing subpar returns on incremental capital; food delivery growth matures; and the market''s very high embedded expectations result in long-term shareholder returns below business growth.',
    'The sustainable steady-state ROCE and free-cash-flow profile of Blinkit after the current expansion phase, and therefore the appropriate long-term valuation for the consolidated group.',
    'Valuation falls to a level where conservative long-term earnings and free-cash-flow assumptions provide a meaningful margin of safety, while Blinkit growth and unit economics remain intact.',
    'For an existing investor, add only when valuation becomes more reasonable or when sustained Blinkit profitability and group-level cash conversion materially exceed current expectations without a corresponding valuation expansion.',
    'Business remains category-leading; Blinkit growth remains strong; food delivery margins remain healthy; group EBITDA converts increasingly into cash; and no material governance issue emerges.',
    'Valuation remains extreme while growth decelerates materially, Blinkit unit economics weaken, or incremental capital requirements rise faster than operating cash generation.',
    'Core competitive position materially deteriorates, Blinkit structurally fails to achieve attractive returns on capital, consolidated economic conversion deteriorates for multiple reporting periods, or a material governance/integrity issue emerges.',
    NULL,
    NULL,
    'WATCH',
    'Eternal is a high-quality, structurally growing business with improving economics, but at approximately INR 328 per share and a very high reported P/E, the market is already pricing in substantial future growth and margin expansion. For a new investment, the appropriate action is WATCH until valuation provides a better margin of safety.',
    '{"factors":[{"name":"Investment Thesis","assessment":"STRONG","narrative":"Eternal can compound through a portfolio of category-leading consumer platforms: Zomato food delivery as the mature cash-generating engine, Blinkit as the high-growth quick-commerce engine, and District/Hyperpure as adjacent optionality.","confidence":"High"}]}'::JSON
);

-- Seed portfolio holdings data
INSERT INTO portfolio_holdings (
    id, name, ticker, sector, qty, avg_cost, invested, value, pe, market_cap,
    w52h, w52l, last_updated, assessment
) VALUES
(
    'EICHERMOT-001',
    'Eicher Motors Limited',
    'EICHERMOT',
    'Automobile · Two-Wheelers',
    17,
    3828.49,
    65084.25,
    137283.50,
    39.82,
    '₹2,19,598 Cr',
    8230.00,
    5825.50,
    '2026-08-19'::DATE,
    '{"thesis":{"moatType":"Brand loyalty","summary":"Eicher''s case rests almost entirely on Royal Enfield''s brand moat in the 250-750cc ''middleweight'' motorcycle segment, where it holds roughly 85-90% share in India and is the global category leader."}}'::JSON
),
(
    'CMSINFO-001',
    'CMS Info Systems Limited',
    'CMSINFO',
    'Financial Services · Cash Logistics',
    179,
    241.74,
    43271.10,
    45152.75,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'BLUESTARCO-001',
    'Blue Star Limited',
    'BLUESTARCO',
    'Consumer Durables · Cooling',
    70,
    533.37,
    37335.88,
    106085.00,
    58.36,
    '₹30,796 Cr',
    2040.00,
    1450.00,
    '2026-08-12'::DATE,
    NULL
),
(
    'ETERNAL-001',
    'Eternal Limited',
    'ETERNAL',
    'Internet · Food Delivery',
    195,
    76.08,
    14835.41,
    63765.00,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
);
